spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
spring:
  datasource:
    url: jdbc:arrow-flight-sql://localhost:32010/?useEncryption=false&disableCertificateVerification=true&user=dremio&password=dremio123
    driver-class-name: org.apache.arrow.driver.jdbc.ArrowFlightJdbcDriver