# SPDX-FileCopyrightText: © 2025 DSLab - Fondazione Bruno Kessler
#
# SPDX-License-Identifier: Apache-2.0

spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
spring:
  datasource:
    url: jdbc:arrow-flight-sql://${DREMIO_URL:localhost:32010/?useEncryption=false&disableCertificateVerification=true&user=dremio&password=dremio123}
    driver-class-name: org.apache.arrow.driver.jdbc.ArrowFlightJdbcDriver
dremio:
  tables: ${DREMIO_TABLES:}